name: Release App
on:
  push:
    tags: ["*"]

env:
  IMAGE_NAME: ghcr.io/myjettools/my-sb-ui

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: myjettools/dioxus-docker:0.6.0
    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF_NAME})


      - name: Updating version
        run: sed -i -e 's/^version = .*/version = "${{ steps.get_version.outputs.VERSION }}"/' Cargo.toml

      - run: |
          export GIT_HUB_TOKEN=${{ secrets.PUBLISH_TOKEN }}
          dx build --platform web --release
          ls ./target/dx/my-sb-ui/release/web
          python3 build.py ./target/dx/my-sb-ui/release/web/public/index.html

      - name: Zip and upload
        run: |
          apt install zip 
          zip -r data.zip ./target/dx/my-sb-ui/release/web ./Dockerfile
          curl -X 'POST' 'https://jetdev.eu/file/my-sb-ui-build.zip' -H 'accept: */*' -H 'Content-Type: multipart/form-data' -F 'file=@data.zip;type=application/zip'
       
#      - name: Upload Build Artifacts
#        uses: actions/upload-artifact@v3
#        with:
#          name: build-artifacts
#          path: |
#            ./target/dx/admin/release/web
#            ./Dockerfile

  publish:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v2    

      - name: Download Build Artifacts
        run: |
          curl -L -o data.zip https://jetdev.eu/file/my-sb-ui-build.zip
          unzip -o data.zip
#        uses: actions/download-artifact@v3
#        with:
#          name: build-artifacts

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF_NAME})          

      - name: Docker login
        run: |          
          echo "${{ secrets.PUBLISH_TOKEN }}" | docker login https://ghcr.io -u "${{ github.actor }}" --password-stdin   
      - name: Docker Build and Publish
        run: |          
          docker build -t ${IMAGE_NAME}:${{ steps.get_version.outputs.VERSION }} .
          docker push ${IMAGE_NAME}:${{ steps.get_version.outputs.VERSION }}
